### ISSUE TITLE
More on Blazored.LocalStorage and file saving to a local PC

### ISSUE THREAD

**Issue by nakigoe** [csharpfritz/csharp_with_csharpfritz#107]
Hi Jeff,
a humble request to elaborate more on Blazored.LocalStorage and file saving to a local PC.
As simple as possible. Saving a few different counters on disk, like in game character stats creation.

**Comment by csharpfritz** [comment]
The demos on the [Blazored.LocalStorage](https://github.com/blazored/LocalStorage) project page are pretty thorough on the scenario you are requesting: how to read and write values in local storage.
