### ISSUE TITLE
Blazor WebAssembly and MVC

### ISSUE THREAD

**Issue by nakigoe** [csharpfritz/csharp_with_csharpfritz#114]
<h1><b>Would MVC help with my Blazor WebAssembly website?</b></h1>

Should I move to exploring other topics than MVC now, since my Blazor WebAssembly website is up and running?

My current pain is pre-rendering for Blazor WebAssembly and finding a free or dirt-cheap server for 0-50 users a day, no more than 25 users accessing the website at the same time.
Or, with GitHub Actions, to crawl and to compile Blazor WebAssembly pages into standard crawlable HTML.

Thanks to Your lessons I've been able to move my static HTML and CSS website into Blazor WebAssembly, and the localization is going smoothly. You can see the fruits of Your teaching here:
<h1><a href="https://nakigoe.org" target="_blank">
<img style="display: block; width: 100%;"
  src="https://nakigoe.org/_IMG/logo-hot.png" 
  srcset="https://nakigoe.org/_IMG/logo-hot.png 4800w,
    https://nakigoe.org/_SRC/logo-hot-3840.png 3840w,
    https://nakigoe.org/_SRC/logo-hot-2560.png 2560w,
    https://nakigoe.org/_SRC/logo-hot-2400.png 2400w,
    https://nakigoe.org/_SRC/logo-hot-2048.png 2048w,
    https://nakigoe.org/_SRC/logo-hot-1920.png 1920w,
    https://nakigoe.org/_SRC/logo-hot-1600.png 1600w,
    https://nakigoe.org/_SRC/logo-hot-1440.png 1440w,
    https://nakigoe.org/_SRC/logo-hot-1280.png 1280w,
    https://nakigoe.org/_SRC/logo-hot-1200.png 1200w,
    https://nakigoe.org/_SRC/logo-hot-1080.png 1080w,
    https://nakigoe.org/_SRC/logo-hot-960.png 960w,
    https://nakigoe.org/_SRC/logo-hot-720.png 720w,
    https://nakigoe.org/_SRC/logo-hot-600.png 600w,
    https://nakigoe.org/_SRC/logo-hot-480.png 480w,
    https://nakigoe.org/_SRC/logo-hot-300.png 300w"
    alt="NAKIGOE.ORG">
<img style="display: block; margin: 0; padding: 0; width: 100%;" 
  src="https://nakigoe.org/_IMG/nakigoe-academy-night.jpg" 
  srcset="https://nakigoe.org/_IMG/nakigoe-academy-night.jpg 2800w,
    https://nakigoe.org/_SRC/nakigoe-academy-night-2048.jpg 2048w"
  alt="Nakigoe Academy">
<img style="display: block; width:  100%;"
    src="https://nakigoe.org/_IMG/logo.png" 
    srcset="https://nakigoe.org/_IMG/logo.png 4800w,
      https://nakigoe.org/_SRC/logo-3840.png 3840w,
      https://nakigoe.org/_SRC/logo-2560.png 2560w,
      https://nakigoe.org/_SRC/logo-2400.png 2400w,
      https://nakigoe.org/_SRC/logo-2048.png 2048w,
      https://nakigoe.org/_SRC/logo-1920.png 1920w,
      https://nakigoe.org/_SRC/logo-1600.png 1600w,
      https://nakigoe.org/_SRC/logo-1440.png 1440w,
      https://nakigoe.org/_SRC/logo-1280.png 1280w,
      https://nakigoe.org/_SRC/logo-1200.png 1200w,
      https://nakigoe.org/_SRC/logo-1080.png 1080w,
      https://nakigoe.org/_SRC/logo-960.png 960w,
      https://nakigoe.org/_SRC/logo-720.png 720w,
      https://nakigoe.org/_SRC/logo-600.png 600w,
      https://nakigoe.org/_SRC/logo-480.png 480w,
      https://nakigoe.org/_SRC/logo-300.png 300w"
    alt="NAKIGOE.ORG">
</a></h1>

**Comment by csharpfritz** [comment]
I can't tell you what your website needs next, that's up to you.  There are lots of things that can be done to enhance and augment your project... and that's for you to decide
