### ISSUE TITLE
User Interface Frameworks

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/csharp_with_csharpfritz#13]
Let's talk about a user interface next.  ... but which one?

Vote with a :+1: on the response that you are interested in seeing first.

Based on the timing of the episodes, this should be a .NET 5 hosted series

**Comment by csharpfritz** [comment]
WPF?

**Comment by csharpfritz** [comment]
Windows Forms?

**Comment by csharpfritz** [comment]
Xamarin for Mobile Applications?

**Comment by csharpfritz** [comment]
ASP.NET Core?

**Comment by csharpfritz** [comment]
Blazor?

**Comment by arashizadi** [comment]
UWP?

**Comment by explorest** [comment]
Avalonia --- its open-source , cross-platform (across windows, linux, mac)  and is C# native [i.e written in, and mainly for C#]

**Comment by csharpfritz** [comment]
Closing.. and setting ASP.NET Core as the topic for Season 2

**Comment by Rshiya** [comment]
blazor maui app??
