### ISSUE TITLE
Add Blazor page to ASP.NET Core MVC project

### ISSUE THREAD

**Issue by wqwalter** [csharpfritz/csharp_with_csharpfritz#141]
In the 10/3/2022 session I asked how to add a Blazor page to a project started as ASP.NET Core MVC. You indicated you would try to show the steps in the next session.

Bill Walter

**Comment by csharpfritz** [comment]
Use the `<component>` tag helper as shown in this page:  https://learn.microsoft.com/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper
