### ISSUE TITLE
Classes vs Structs 👀

### ISSUE THREAD

**Issue by cecilphillip** [csharpfritz/csharp_with_csharpfritz#4]
I've been getting a lot of questions from students on the usage of class vs structs. We have a doc [here](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct) that discusses the topic. 

Personally, I don't think I've ever created a struct for a production application. I'd love to hear/see some practical usage of where one is better suited than the other.

**Comment by csharpfritz** [comment]
Let's do a whole stream JUST on structs.  When to use them, the differences between structs and classes, etc.

**Comment by cecilphillip** [comment]
Perfect. I can use that video as a reference for our student partners

**Comment by csharpfritz** [comment]
Also talk about enums

**Comment by csharpfritz** [comment]
Add a section on creating Generic methods
