### ISSUE TITLE
Add dev container support

### ISSUE THREAD

**Issue by NikiforovAll** [csharpfritz/csharp_with_csharpfritz#44]
I think it would be nice to have dev container configuration added. 

This repository is already containerized and dev container adds features on top of it. 

Ref🔗: <https://code.visualstudio.com/docs/remote/create-dev-container>

---
I'd be happy to contribute.

**Comment by NikiforovAll** [comment]
Something like this, actually: <https://github.com/NikiforovAll/csharp_workshop>

**Comment by csharpfritz** [comment]
Looks like a pretty good idea, and something to be considered when 'real projects' start on stream.

I would be interested in a PR if you'd like send one
