### ISSUE TITLE
Web API Series

### ISSUE THREAD

**Issue by MaciejWiatr** [csharpfritz/csharp_with_csharpfritz#79]
Hello, as the REST API becomes a standard of today's web communication, I would really love to see an in-deph series about it. 
Here are some lesson ideas: 
- User authentication with JWT and secondary providers like google
- Caching
- Pagination
- Deployment (incl. deploying on linux)
- Clean project architecture
- File upload
- Interaction with frontend frameworks
Let me know what you think :)

**Comment by csharpfritz** [comment]
This might be something very cool to plan and cohost with @spboyer

Let me chat with Shayne and a few folks and see where we can fit this in

Jeff

**Comment by spboyer** [comment]
Who me? I'm in. :-)
