### ISSUE TITLE
[Question] About Jupyter Notebooks, github, binder and VS Code

### ISSUE THREAD

**Issue by ethedy** [csharpfritz/csharp_with_csharpfritz#92]
Hello Jeff, as you can see in the "header" the "content-length" of my "request" is too long... 😉 

First, I want to thank you and congratulate for the passion, dedication and tech detail in your live streamings, good job!

Second, if you can at some time in the near future, explain about the end-to-end process for get the same configuration just like [your repository](https://github.com/csharpfritz/csharp_with_csharpfritz/tree/main/notebooks): how can I deploy or set the notebooks in github with binder support, and also get the same locally with VS Code with and without docker.
I am a humble instructor of C# in a non-profit organization in my city (Rosario, Argentina) and I wish to replicate your teach technique, at least for the basics concepts of the language

Thanks again!

PS: I originally post the same question in Fritz.LiveStream by mistake. Sorry

**Comment by csharpfritz** [comment]
Check out the instructions and readme in the .NET Interactive repository:  https://github.com/dotnet/interactive

Thanks for the question!

**Comment by ethedy** [comment]
And thanks for the reply!
