### ISSUE TITLE
Blazor to Azure sql database 

### ISSUE THREAD

**Issue by ugogroup** [csharpfritz/csharp_with_csharpfritz#97]
Hi Jeff

Is it possible to teach us How can we Securely connect Blazor to Azure sql database in such a way that can not be hacked.  

Thanks in advance.

**Comment by csharpfritz** [comment]
This will be covered in today's session on Blazor with Data.

YouTube link at https://www.youtube.com/watch?v=JYHyaATn4IY

**Comment by ugogroup** [comment]
Thanks a lot Jeff. We appreciate  your service. You are the best 🥇

**Comment by csharpfritz** [comment]
We're going to use Sqlite for the demo today, but the same concepts apply
to SQL Server or any other relational database you wish to use


Jeff

**Comment by ugogroup** [comment]
Is it the same as connecting to a cloud based database?
